import type { Metadata } from 'next';

import { Providers } from './Providers';
import Header from '@/modules/header/Header';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center w-full h-screen relative">
        <Providers>
          <Header />
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
